name: 'Slack Notification'
description: 'Send slack notification about the new release'
inputs:
  SLACK_WEBHOOK:
    description: 'Slack webhook'
    required: true
  SHORTCUT_LINKS:
    description: 'List of links to shortcut stories'
    required: true
  CHANGELOG:
    description: 'List of merged PRs'
    required: true
  VERSION:
    description: 'Release version'
    required: true
  RELEASE_URL:
    description: 'Github release url'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'