name: "Github Release"
description: "Publish Github releases from an action"

inputs:
  TARGET_COMMIT_SHA:
    description: 'Target commit SHA for this deploy'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
