name: "Github Release"
description: "Publish Github releases from an action"

inputs:
  title:
    description: "The name of the release to publish"
    required: true

runs:
  using: 'composite'
  steps:      
    - run: hub release create -m "$(date +%Y%m%d.%H%M%S)" ${INPUT_CHANGELOG}
      shell: bash
      env:
        CHANGELOG: ${{ inputs.changelog }}
