name: "Github Release"
description: "Publish Github releases from an action"

inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
  TARGET_COMMIT_SHA:
    description: 'Target commit SHA for this deploy'
    required: true

runs:
  using: 'node14'
  main: 'dist/index.js'
