name: "Github Release"
description: "Publish Github releases from an action"

inputs:
  RELEASE_TOKEN:
    description: 'Github token for release creation'
    required: true
  TARGET_COMMIT_SHA:
    description: 'Target commit SHA for this deploy'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
