name: "Github Release"
description: "Publish Github releases from an action"

inputs:
  title:
    description: "The name of the release to publish"
    required: true

runs:
  using: 'composite'
  steps:      
    - run: hub release create -m "${INPUT_TITLE}" "$(date +%Y%m%d%H%M%S)"
      shell: bash
      env:
        INPUT_TITLE: ${{ inputs.title }}
