name: Publish New Release
on:
  repository_dispatch:
    types: [release]

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create a Release
        uses: ./.github/actions/releases
        id: releases
        continue-on-error: true
        with:
          TARGET_COMMIT_SHA:
            ${{ github.event.client_payload.TARGET_COMMIT_SHA }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Wait after failure
        id: wait
        if: ${{ failure() }}
        run: |
          sleep 300
          echo "Done waiting for 5 minutes"
          echo "::set-output name=rerun::true"
      - name: Retry Create a Release
        uses: ./.github/actions/releases
        id: releases
        if: ${{ steps.wait.outputs.rerun == 'true' }}
        with:
          TARGET_COMMIT_SHA:
            ${{ github.event.client_payload.TARGET_COMMIT_SHA }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack notification
        uses: ./.github/actions/slack
        id: slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          SHORTCUT_LINKS: ${{ steps.releases.outputs.SHORTCUT_LINKS }}
          CHANGELOG: ${{ steps.releases.outputs.CHANGELOG }}
          VERSION: ${{ steps.releases.outputs.VERSION }}
          RELEASE_URL: ${{ steps.releases.outputs.RELEASE_URL }}
