name: Publish Release
on:
  repository_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create a Release
      uses: ./.github/actions/releases
      with:
        RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        TARGET_COMMIT_SHA: ${{ github.event.client_payload.TARGET_COMMIT_SHA }}

