name: Publish New Release
on:
  repository_dispatch:
    types: [release]

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create a Release
        uses: ./.github/actions/releases
        id: releases
        with:
          TARGET_COMMIT_SHA:
            ${{ github.event.client_payload.TARGET_COMMIT_SHA }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack notification
        uses: ./.github/actions/slack
        id: slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          SHORTCUT_LINKS: ${{ steps.releases.outputs.SHORTCUT_LINKS }}
          CHANGELOG: ${{ steps.releases.outputs.CHANGELOG }}
          VERSION: ${{ steps.releases.outputs.VERSION }}
          RELEASE_URL: ${{ steps.releases.outputs.RELEASE_URL }}
