name: Publish New Release
on:
  repository_dispatch:
    types: [release]

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create a Release
        run: exit 1
        continue-on-error: true
      - name: Wait
        id: wait
        if: ${{ failure() }}
        run: |
          sleep 15
      - name: Retry Create a Release
        uses: ./.github/actions/releases
        with:
          TARGET_COMMIT_SHA:
            ${{ github.event.client_payload.TARGET_COMMIT_SHA }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack notification
        uses: ./.github/actions/slack
        id: slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

